server:
  port: 8070
  servlet:
    context-path: /
spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.105:7006/test_lu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: ENC(EMucuoWhXKzMq7nnVjk4UqorqUdwPdL8+fwzfClOVeeCWLESZZUEQb0CdhUDbtJX)
    password: ENC(/W5LPa5ejLrDld80RS4mnrypxtTm2LH3hX8qGaxgzCSQNWOVhpPqqi1EvCoBthgQ)

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

reformer:
  gecko:
    auto-table:
      ddl-auto: update
      scan-package: org.gecko.reformer.entity

#logging:
#  level:
#    org.gecko.reformer: debug


