server:
  port: 8081

spring:
  application:
    name: canal-client

reformer:
  gecko:
    canal:
      enable: true
      async: false
      server: 127.0.0.1:11111
      destination: canalClient8081
      filter: test_lu_1\..*
